services:
  mongodb:
    image: mongo:6
    container_name: taskrunner-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - taskrunner-net

  redis:
    image: redis:7-alpine
    container_name: taskrunner-redis
    ports:
      - "6379:6379"
    networks:
      - taskrunner-net

  minio:
    image: minio/minio:latest
    container_name: taskrunner-minio
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - taskrunner-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-create-bucket:
    image: minio/mc:latest
    container_name: taskrunner-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/task-logs --ignore-existing;
      exit 0;
      "
    networks:
      - taskrunner-net

  backend:
    build: ./backend
    container_name: taskrunner-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - mongodb
      - redis
    networks:
      - taskrunner-net

  web:
    build: ./web
    container_name: taskrunner-web
    ports:
      - "5001:5000"
    env_file:
      - ./web/.env
    volumes:
      - ./web/app:/app/app
    depends_on:
      - backend
    networks:
      - taskrunner-net

  worker:
    build: ./worker
    container_name: taskrunner-worker
    env_file:
      - ./worker/.env
    volumes:
      - ./worker/app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
      - redis
    networks:
      - taskrunner-net

volumes:
  mongo_data:
  minio_data:

networks:
  taskrunner-net:
    driver: bridge
